# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a585b455d95ac42c32909ac8036ce19"
application_url = "https://crush-candy-production.up.railway.app"
embedded = true
name = "Crush Candy Supplies"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [ "https://crush-candy-production.up.railway.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
