name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npm run db:generate"
dev = "npm run db:migrate:deploy && npm exec react-router dev"
