CREATE TYPE "DistanceMethod" AS ENUM ('STRAIGHT_LINE', 'DRIVING');
CREATE TYPE "KmRounding" AS ENUM ('EXACT', 'CEIL', 'FLOOR', 'NEAREST');
ALTER TABLE "AppSettings"
  ADD COLUMN "baseLatitude" DECIMAL(65,30), ADD COLUMN "baseLongitude" DECIMAL(65,30),
  ADD COLUMN "deliveryEnabled" BOOLEAN NOT NULL DEFAULT true, ADD COLUMN "distanceMethod" "DistanceMethod",
  ADD COLUMN "kmRoundingMode" "KmRounding", ADD COLUMN "minDeliverySpendCents" INTEGER NOT NULL DEFAULT 25000,
  ADD COLUMN "over55BaseCents" INTEGER NOT NULL DEFAULT 12000, ADD COLUMN "over55PerKmCents" INTEGER NOT NULL DEFAULT 300,
  ADD COLUMN "processingWindowHours" INTEGER NOT NULL DEFAULT 24, ADD COLUMN "tier25To40Cents" INTEGER NOT NULL DEFAULT 7500,
  ADD COLUMN "tier40To55Cents" INTEGER NOT NULL DEFAULT 12000, ADD COLUMN "tierUnder25Cents" INTEGER NOT NULL DEFAULT 5000;
