import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useLoaderData } from "react-router";
import { useMemo, useState } from "react";
import { requireAdmin } from "../auth/admin.server";
import { AnnouncementAudience, AnnouncementStatus, listAllAnnouncements, saveAnnouncement } from "../services/content-support.server";

export async function loader({ request }: LoaderFunctionArgs) { await requireAdmin(request); return { announcements: await listAllAnnouncements() }; }
export async function action({ request }: ActionFunctionArgs) { const { session } = await requireAdmin(request); const f = Object.fromEntries(await request.formData()); try { await saveAnnouncement({ id: typeof f.id === "string" && f.id ? f.id : undefined, audience: f.audience === "DRIVER" ? AnnouncementAudience.DRIVER : AnnouncementAudience.CUSTOMER, status: f.status === "PUBLISHED" ? AnnouncementStatus.PUBLISHED : AnnouncementStatus.DRAFT, title: String(f.title ?? ""), body: String(f.body ?? ""), sortOrder: Number(f.sortOrder ?? 0), actorId: session.id }); return { ok: true, message: "Announcement saved." }; } catch (e) { return { ok: false, message: e instanceof Error ? e.message : "Could not save announcement" }; } }

export default function Announcements() {
  const { announcements } = useLoaderData<typeof loader>(); const result = useActionData<typeof action>(); const [view, setView] = useState("ALL");
  const visible = useMemo(() => announcements.filter((announcement) => view === "ALL" || announcement.audience === view), [announcements, view]);
  const published = announcements.filter((announcement) => announcement.status === "PUBLISHED").length;
  const customers = announcements.filter((announcement) => announcement.audience === "CUSTOMER").length;
  const drivers = announcements.filter((announcement) => announcement.audience === "DRIVER").length;
  return <s-page heading="Announcements" inlineSize="large"><s-stack direction="block" gap="base">
    <s-section><s-stack direction="block" gap="small"><s-heading>Content workspace</s-heading><s-text>Publish separate notices for customers and drivers. Audience filtering is enforced server-side on each recipient surface.</s-text></s-stack></s-section>
    {result?.message ? <s-section><s-banner tone={result.ok ? "success" : "critical"}>{result.message}</s-banner></s-section> : null}
    <s-section heading="Overview"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 12 }}>{[["Total", announcements.length], ["Published", published], ["Customer", customers], ["Driver", drivers]].map(([label, value]) => <div key={label} style={{ border: "1px solid #e1e3e5", borderRadius: 8, padding: 16, background: "#fff" }}><s-text>{label}</s-text><div style={{ fontSize: 28, fontWeight: 650, marginTop: 8 }}>{value}</div></div>)}</div></s-section>
    <s-section heading="Create announcement"><s-text>Choose the audience carefully: customers see notices in the approved customer portal; drivers see notices in the Driver portal.</s-text><Form method="post" style={{ display: "grid", gap: 12, maxWidth: 700, marginTop: 16 }}><label>Audience<select name="audience" defaultValue="CUSTOMER"><option value="CUSTOMER">Customer — approved customers</option><option value="DRIVER">Driver — active drivers</option></select></label><label>Title<input name="title" required maxLength={180} placeholder="Short, descriptive title" /></label><label>Message<textarea name="body" required maxLength={4000} rows={5} placeholder="Write the announcement message" /></label><label>Publishing status<select name="status" defaultValue="DRAFT"><option value="DRAFT">Draft — not visible</option><option value="PUBLISHED">Published — visible to selected audience</option></select></label><div><s-button type="submit" variant="primary">Save announcement</s-button></div></Form></s-section>
    <s-section heading="Announcement library"><s-stack direction="block" gap="base"><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}><s-button type="button" variant={view === "ALL" ? "primary" : "secondary"} onClick={() => setView("ALL")}>All ({announcements.length})</s-button><s-button type="button" variant={view === "CUSTOMER" ? "primary" : "secondary"} onClick={() => setView("CUSTOMER")}>Customers ({customers})</s-button><s-button type="button" variant={view === "DRIVER" ? "primary" : "secondary"} onClick={() => setView("DRIVER")}>Drivers ({drivers})</s-button></div>{announcements.length === 0 ? <div style={{ padding: 28, textAlign: "center" }}><s-heading>No announcements yet</s-heading><s-text>Create the first customer or driver notice above.</s-text></div> : visible.length === 0 ? <div style={{ padding: 24, textAlign: "center" }}><s-text>No announcements match this audience.</s-text></div> : <div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse", minWidth: 680 }}><thead><tr><th style={{ textAlign: "left", padding: 10 }}>Announcement</th><th style={{ textAlign: "left", padding: 10 }}>Audience</th><th style={{ textAlign: "left", padding: 10 }}>Status</th><th style={{ textAlign: "left", padding: 10 }}>Created</th></tr></thead><tbody>{visible.map((announcement) => <tr key={announcement.id} style={{ borderTop: "1px solid #e1e3e5" }}><td style={{ padding: 10 }}><strong>{announcement.title}</strong><div style={{ color: "#616161", fontSize: 13, maxWidth: 460, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{announcement.body}</div></td><td style={{ padding: 10 }}><s-badge tone={announcement.audience === "CUSTOMER" ? "info" : "neutral"}>{announcement.audience === "CUSTOMER" ? "Customer" : "Driver"}</s-badge></td><td style={{ padding: 10 }}><s-badge tone={announcement.status === "PUBLISHED" ? "success" : "warning"}>{announcement.status === "PUBLISHED" ? "Published" : "Draft"}</s-badge></td><td style={{ padding: 10 }}>{new Date(announcement.createdAt).toLocaleString("en-AU", { timeZone: "Australia/Perth" })}</td></tr>)}</tbody></table></div>}</s-stack></s-section>
  </s-stack></s-page>;
}
