/* eslint-disable jsx-a11y/label-has-associated-control */
import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useLoaderData } from "react-router";
import { requireAdmin } from "../auth/admin.server";
import { getDeliverySettings, saveDeliverySettings } from "../services/delivery.server";
import { getServerEnvironment } from "../config/env.server";

export async function loader({ request }: LoaderFunctionArgs) { await requireAdmin(request); const settings = await getDeliverySettings(); const env = getServerEnvironment(); return { settings, providerConfigured: Boolean(env.DISTANCE_PROVIDER && env.DISTANCE_API_KEY), originConfigured: Boolean(env.DELIVERY_ORIGIN_LATITUDE && env.DELIVERY_ORIGIN_LONGITUDE), carrierConfigured: env.SCOPES.split(",").map((scope) => scope.trim()).includes("write_shipping") }; }
export async function action({ request }: ActionFunctionArgs) {
  await requireAdmin(request); const f = await request.formData(); const num = (key: string) => Number(f.get(key));
  const method = String(f.get("distanceMethod") || ""); const rounding = String(f.get("kmRoundingMode") || "");
  if (!["", "STRAIGHT_LINE", "DRIVING"].includes(method) || !["", "EXACT", "CEIL", "FLOOR", "NEAREST"].includes(rounding)) return { ok: false, message: "Invalid distance configuration." };
  try { await saveDeliverySettings({ deliveryEnabled: f.get("deliveryEnabled") === "on", minDeliverySpendCents: num("minDeliverySpendCents"), distanceMethod: method ? method as "STRAIGHT_LINE" | "DRIVING" : null, kmRoundingMode: rounding ? rounding as "EXACT" | "CEIL" | "FLOOR" | "NEAREST" : null, tierUnder25Cents: num("tierUnder25Cents"), tier25To40Cents: num("tier25To40Cents"), tier40To55Cents: num("tier40To55Cents"), over55BaseCents: num("over55BaseCents"), over55PerKmCents: num("over55PerKmCents") }); return { ok: true, message: "Delivery settings saved." }; } catch { return { ok: false, message: "Invalid delivery settings." }; }
}
export default function DeliverySettings() {
  const { settings, providerConfigured, originConfigured, carrierConfigured } = useLoaderData<typeof loader>(); const result = useActionData<typeof action>();
  const s = settings ?? { deliveryEnabled: true, minDeliverySpendCents: 25000, tierUnder25Cents: 5000, tier25To40Cents: 7500, tier40To55Cents: 12000, over55BaseCents: 12000, over55PerKmCents: 300, distanceMethod: "DRIVING" as const, kmRoundingMode: "CEIL" as const };
  const money = (cents: number) => `AUD $${(cents / 100).toFixed(2)}`;
  const rules = [["Under 25 km", money(s.tierUnder25Cents)], ["25–40 km", money(s.tier25To40Cents)], [">40–55 km", money(s.tier40To55Cents)], [">55 km", `${money(s.over55BaseCents)} + ${money(s.over55PerKmCents)} / additional km`]];
  const fields = [["Minimum order (cents)", "minDeliverySpendCents", s.minDeliverySpendCents], ["Under 25 km (cents)", "tierUnder25Cents", s.tierUnder25Cents], ["25–40 km (cents)", "tier25To40Cents", s.tier25To40Cents], [">40–55 km (cents)", "tier40To55Cents", s.tier40To55Cents], [">55 base (cents)", "over55BaseCents", s.over55BaseCents], ["Additional km (cents)", "over55PerKmCents", s.over55PerKmCents]] as const;
  return <s-page heading="Delivery settings" inlineSize="large"><s-stack direction="block" gap="base">
    <s-section><s-stack direction="block" gap="small"><s-heading>Delivery configuration</s-heading><s-text>Manage the rules used for Perth delivery pricing. Private origin and provider credentials remain server-side only.</s-text></s-stack></s-section>
    {result?.message ? <s-section><s-banner tone={result.ok ? "success" : "critical"}>{result.message}</s-banner></s-section> : null}
    <s-section heading="Current status"><div style={{ display: "flex", flexWrap: "wrap", gap: 10 }}><s-badge tone={s.deliveryEnabled ? "success" : "critical"}>Delivery · {s.deliveryEnabled ? "Enabled" : "Disabled"}</s-badge><s-badge tone="info">Minimum · AUD $250</s-badge><s-badge tone={s.distanceMethod === "DRIVING" ? "success" : "critical"}>Distance · {s.distanceMethod === "DRIVING" ? "Driving / road" : "Not production-ready"}</s-badge><s-badge tone={s.kmRoundingMode === "CEIL" ? "success" : "warning"}>Over 55 km · {s.kmRoundingMode === "CEIL" ? "Round up" : s.kmRoundingMode ?? "Not configured"}</s-badge></div></s-section>
    <s-section heading="Delivery pricing rules"><div style={{ display: "grid", gap: 8 }}>{rules.map(([range, price]) => <div key={range} style={{ display: "flex", justifyContent: "space-between", gap: 16, padding: "12px 0", borderBottom: "1px solid #e1e3e5" }}><s-text>{range}</s-text><strong>{price}</strong></div>)}</div><s-text><small>Additional distance rounds up: 55.1 km adds 1 km; 56.1 km adds 2 km.</small></s-text></s-section>
    <s-section heading="Rules and calculation method"><Form method="post"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 12 }}>{fields.map(([label, name, value]) => <label key={name}>{label}<input name={name} type="number" min="0" defaultValue={Number(value)} /></label>)}</div><div style={{ display: "flex", flexWrap: "wrap", gap: 16, marginTop: 16 }}><label>Distance method<select name="distanceMethod" defaultValue={s.distanceMethod ?? ""}><option value="">Not configured</option><option value="DRIVING">Driving / road distance (required)</option><option value="STRAIGHT_LINE">Straight line (not permitted in production)</option></select></label><label>Extra-km rounding<select name="kmRoundingMode" defaultValue={s.kmRoundingMode ?? ""}><option value="">Not configured</option><option value="CEIL">Round up (required)</option><option value="EXACT">Exact</option><option value="FLOOR">Round down</option><option value="NEAREST">Nearest</option></select></label></div><div style={{ marginTop: 16 }}><input type="checkbox" name="deliveryEnabled" defaultChecked={s.deliveryEnabled} /> <label>Delivery enabled</label></div><div style={{ marginTop: 16 }}><s-button type="submit" variant="primary">Save delivery rules</s-button></div></Form></s-section>
    <s-section heading="Private origin and distance provider"><div style={{ display: "grid", gap: 10 }}><div><strong>Private origin</strong> <s-badge tone={originConfigured ? "success" : "warning"}>{originConfigured ? "Configured server-side" : "Not configured"}</s-badge><p><small>The Mirrabooka base coordinates are never displayed to customers or returned by this page.</small></p></div><div><strong>Driving provider</strong> <s-badge tone={providerConfigured ? "success" : "warning"}>{providerConfigured ? "Credentials configured" : "Credentials missing"}</s-badge><p><small>Actual road-distance pricing remains unavailable until a driving provider and credentials are configured. Secrets are never displayed.</small></p></div></div></s-section>
    <s-section heading="Shopify checkout integration"><div style={{ display: "grid", gap: 10 }}><div><strong>Carrier Service</strong> <s-badge tone={carrierConfigured ? "success" : "warning"}>{carrierConfigured ? "Scope configured" : "Pending merchant verification"}</s-badge><p><small>Registration and shipping-profile attachment are merchant-controlled and are not performed by this page.</small></p></div><div><strong>Postcode-zone fallback</strong> <s-badge tone="info">Shopify-managed</s-badge><p><small>Approximate postcode zones must be configured in a Shopify shipping profile if Carrier Service is unavailable. The app does not manage those zones.</small></p></div></div></s-section>
  </s-stack></s-page>;
}
