import type { LoaderFunctionArgs } from "react-router";
import { Form, Link, useLoaderData } from "react-router";
import { useMemo, useState } from "react";
import { requireAdmin } from "../auth/admin.server";
import { adminSearchConversations } from "../services/chat.server";

export async function loader({ request }: LoaderFunctionArgs) { await requireAdmin(request); const query = new URL(request.url).searchParams.get("q") ?? undefined; return { conversations: await adminSearchConversations(query), query: query ?? "" }; }

export default function AdminChats() {
  const { conversations, query } = useLoaderData<typeof loader>();
  const [status, setStatus] = useState("ALL");
  const visible = useMemo(() => conversations.filter((conversation) => status === "ALL" || status === "OPEN" && conversation.status === "OPEN" || status === "CLOSED" && conversation.status !== "OPEN"), [conversations, status]);
  const active = conversations.filter((conversation) => conversation.status === "OPEN").length;
  const closed = conversations.length - active;
  return <s-page heading="Chat oversight" inlineSize="large"><s-stack direction="block" gap="base">
    <s-section><s-stack direction="block" gap="small"><s-heading>Customer-driver conversations</s-heading><s-text>Search and review delivery conversations. Admin access is read-only and every conversation read is audit logged.</s-text></s-stack></s-section>
    <s-section heading="Overview"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 12 }}>{[["Recent conversations", conversations.length], ["Active", active], ["Closed / completed", closed]].map(([label, value]) => <div key={label} style={{ border: "1px solid #e1e3e5", borderRadius: 8, padding: 16, background: "#fff" }}><s-text>{label}</s-text><div style={{ fontSize: 28, fontWeight: 650, marginTop: 8 }}>{value}</div></div>)}</div></s-section>
    <s-section heading="Find a conversation"><Form method="get" style={{ display: "flex", gap: 8, alignItems: "end", flexWrap: "wrap" }}><label>Order number or Shopify order ID<input name="q" defaultValue={query} maxLength={100} placeholder="e.g. #1001" /></label><s-button type="submit" variant="primary">Search</s-button>{query ? <Link to="/app/chat">Clear search</Link> : null}</Form></s-section>
    <s-section heading="Conversation inbox"><s-stack direction="block" gap="base"><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}><s-button type="button" variant={status === "ALL" ? "primary" : "secondary"} onClick={() => setStatus("ALL")}>All ({conversations.length})</s-button><s-button type="button" variant={status === "OPEN" ? "primary" : "secondary"} onClick={() => setStatus("OPEN")}>Active ({active})</s-button><s-button type="button" variant={status === "CLOSED" ? "primary" : "secondary"} onClick={() => setStatus("CLOSED")}>Closed ({closed})</s-button></div>{conversations.length === 0 ? <div style={{ padding: 28, textAlign: "center" }}><s-heading>{query ? "No conversations found" : "No conversations yet"}</s-heading><s-text>{query ? "Try a different order reference or clear the search." : "Conversations will appear when a delivery chat is created."}</s-text></div> : visible.length === 0 ? <div style={{ padding: 24, textAlign: "center" }}><s-text>No conversations match this view.</s-text></div> : <div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse", minWidth: 680 }}><thead><tr><th style={{ textAlign: "left", padding: 10 }}>Order</th><th style={{ textAlign: "left", padding: 10 }}>Participants</th><th style={{ textAlign: "left", padding: 10 }}>Status</th><th style={{ textAlign: "left", padding: 10 }}>Last activity</th><th style={{ textAlign: "left", padding: 10 }}>Action</th></tr></thead><tbody>{visible.map((conversation) => { const last = conversation.messages.at(-1); return <tr key={conversation.id} style={{ borderTop: "1px solid #e1e3e5" }}><td style={{ padding: 10 }}><strong>{conversation.assignment.shopifyOrderNumber}</strong><div style={{ color: "#616161", fontSize: 13 }}>{conversation.shopifyCustomerId}</div></td><td style={{ padding: 10 }}>Customer · {conversation.assignment.driver?.displayName ?? "Unassigned"}</td><td style={{ padding: 10 }}><s-badge tone={conversation.status === "OPEN" ? "success" : "neutral"}>{conversation.status === "OPEN" ? "Active" : "Closed"}</s-badge></td><td style={{ padding: 10 }}>{last ? <><div style={{ maxWidth: 280, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{last.body}</div><small>{new Date(last.createdAt).toLocaleString("en-AU", { timeZone: "Australia/Perth" })}</small></> : "No messages"}</td><td style={{ padding: 10 }}><Link to={`/app/chat/${conversation.id}`}>Open history</Link></td></tr>; })}</tbody></table></div>}</s-stack></s-section>
  </s-stack></s-page>;
}
