import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, useLoaderData } from "react-router";
import { authenticateCustomerProxy } from "../auth/customer.server";
import { getCustomerApprovalState } from "../services/customer/approval.server";
import { getCustomerConversation, markConversationRead, sendMessage } from "../services/chat.server";

export async function loader({ request, params }: LoaderFunctionArgs) { const context = await authenticateCustomerProxy(request); if (!context.shopifyCustomerId) throw new Response("Login required", { status: 401 }); if (!(await getCustomerApprovalState(context.admin, context.shopifyCustomerId)).approved) throw new Response("Approval required", { status: 403 }); const conversation = await getCustomerConversation(params.id ?? "", context.shopifyCustomerId); if (!conversation) throw new Response("Not found", { status: 404 }); await markConversationRead(conversation.id, "CUSTOMER", context.shopifyCustomerId, conversation.messages.at(-1)?.id); return { conversation }; }
export async function action({ request, params }: ActionFunctionArgs) { const context = await authenticateCustomerProxy(request); if (!context.shopifyCustomerId) throw new Response("Login required", { status: 401 }); const form = await request.formData(); const intent = String(form.get("intent")); const conversation = await getCustomerConversation(params.id ?? "", context.shopifyCustomerId); if (!conversation) throw new Response("Not found", { status: 404 }); if (intent === "read") { await markConversationRead(conversation.id, "CUSTOMER", context.shopifyCustomerId, String(form.get("messageId") || "")); return { ok: true }; } await sendMessage({ conversationId: conversation.id, senderType: "CUSTOMER", senderId: context.shopifyCustomerId, senderLabel: "Customer", body: String(form.get("body") ?? "") }); return { ok: true }; }
export default function CustomerChat() { const { conversation } = useLoaderData<typeof loader>(); return <><h1>Delivery chat · {conversation.assignment.shopifyOrderNumber}</h1><p><strong>Privacy reminder:</strong> Chat is for arrival and delivery communication. Do not share personal/contact information with drivers. Protect yourself from scams and keep communication inside the platform.</p><section aria-live="polite">{conversation.messages.map((m) => <p key={m.id}><strong>{m.senderLabel}</strong> · {new Date(m.createdAt).toLocaleString("en-AU", { timeZone: "Australia/Perth" })}<br />{m.body}</p>)}</section><Form method="post"><textarea name="body" maxLength={2000} required aria-label="Message" /><button type="submit">Send</button></Form></>; }
