import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, redirect, useLoaderData } from "react-router";
import { requireDriver } from "../auth/driver.server";
import { createDriverCsrfToken } from "../lib/driver-security.server";
import { requireDriverCsrf } from "../services/driver/auth.server";
import { getDriverConversation, markConversationRead, sendMessage } from "../services/chat.server";

export async function loader({ request, params }: LoaderFunctionArgs) { try { const auth = await requireDriver(request); const conversation = await getDriverConversation(params.id ?? "", auth.context.driverId); if (!conversation) throw new Response("Not found", { status: 404 }); await markConversationRead(conversation.id, "DRIVER", auth.context.driverId, conversation.messages.at(-1)?.id); return { conversation, csrfToken: createDriverCsrfToken(auth.context.sessionId) }; } catch (error) { if (error instanceof Response && error.status === 404) throw error; throw redirect("/driver/login"); } }
export async function action({ request, params }: ActionFunctionArgs) { const auth = await requireDriver(request); const form = await request.formData(); requireDriverCsrf(request, auth, String(form.get("csrfToken") ?? "")); const conversation = await getDriverConversation(params.id ?? "", auth.context.driverId); if (!conversation) throw new Response("Not found", { status: 404 }); const intent = String(form.get("intent")); if (intent === "read") { await markConversationRead(conversation.id, "DRIVER", auth.context.driverId, String(form.get("messageId") || "")); return { ok: true }; } await sendMessage({ conversationId: conversation.id, senderType: "DRIVER", senderId: auth.context.driverId, senderLabel: auth.context.displayName, body: String(form.get("body") ?? "") }); return { ok: true }; }
export default function DriverChat() { const { conversation, csrfToken } = useLoaderData<typeof loader>(); return <main style={{ maxWidth: 760, margin: "0 auto", padding: 32 }}><h1>Delivery chat · {conversation.assignment.shopifyOrderNumber}</h1><p>Use this chat for ETA, arrival, and drop-off communication. Keep contact details inside the platform.</p>{conversation.messages.map((m) => <p key={m.id}><strong>{m.senderLabel}</strong> · {new Date(m.createdAt).toLocaleString("en-AU", { timeZone: "Australia/Perth" })}<br />{m.body}</p>)}<Form method="post"><input type="hidden" name="csrfToken" value={csrfToken} /><textarea name="body" maxLength={2000} required /><button type="submit">Send</button></Form></main>; }
